services:
  postgres:
    container_name: postgres-testing
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_testing_data:/var/lib/postgresql/data
volumes:
  postgres_testing_data:
