services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: postgres
  valkey:
    image: valkey/valkey:latest
    ports:
      - 5433:6379
